ansible_pubkey:
  ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIBKzrh3bKiZyQctl3v1SWmVaxikx0WP830lycLP4phZz morten@MSO-PC-Debian
  ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIJ9xo+W4xw1xJmtoMsd4Dr4LPJdOYPqSYUyhT2wGBePD frede@HEAD9XDesktop
  ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIEvBc0WWp2iru8P7HeuwGV7DybggvjTCWpAlgYYIC+m9 wt13df@student.aau.dk
  ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAINYaBIwpqe+/T2Arm3eQ34qQHF3rTln/wSNgqVUeHbLh u0_a483@localhost-kejsphone
